/**
 * SENTINEL APEX — Intel Data Loader + Tier-Based Content Filter
 * Reads from static JSON files generated by the pipeline.
 * Phase 4: Paid Intel Segmentation — enforces Free/Pro/Enterprise access.
 * Phase 7: Trust & Verification — source attribution + confidence on every item.
 */
'use strict';
const { isCloudflareWorkers } = require('./runtime-env');
const { tierAtLeast, dataProfile } = require('./tier-entitlements');
const { applyRecordCorrections } = require('./cvss-corrections');

// Paths to static intel files (generated by fetch-live-intel.js).
//
// Workers has no filesystem, so __dirname-based fs.readFileSync (the
// unchanged Node/Vercel path below) throws ReferenceError: __dirname is
// not defined there (confirmed via a real `wrangler dev` run, not
// assumed). PATHS holds the already-PARSED data instead of path strings
// on that branch — require('*.json') is bundled at build time (esbuild
// has native JSON support, no wrangler.jsonc `rules` entry needed) and
// self-memoizes, so loadJSON() below just returns it as-is with no fs
// call and no TTL cache of its own.
//
// This does mean intel data on Workers only refreshes on a new Worker
// deploy, not on every git push the way Vercel's per-file fs reads do —
// see the deployment-frequency policy doc for the tradeoff this forces.
let PATHS;
if (isCloudflareWorkers()) {
  PATHS = {
    live:        require('../intel/live.json'),
    topThreats:  require('../intel/top-threats.json'),
    iocs:        require('../intel/iocs.json'),
    ransomware:  require('../intel/ransomware.json'),
    liveWidget:  require('../../live-intel.json'),
    state:       require('../../intel-state.json'),
    graph:       require('../intel/threat-graph.json'),
    campaigns:   require('../intel/campaigns.json'),
    reportsIndex: require('../intel/reports-index.json'),
    cveEnrichment: require('../intel/cve-enrichment-index.json'),
  };
} else {
  const path = require('path');
  const BASE = path.resolve(__dirname, '../../');
  PATHS = {
    live:        path.join(BASE, 'api', 'intel', 'live.json'),
    topThreats:  path.join(BASE, 'api', 'intel', 'top-threats.json'),
    iocs:        path.join(BASE, 'api', 'intel', 'iocs.json'),
    ransomware:  path.join(BASE, 'api', 'intel', 'ransomware.json'),
    liveWidget:  path.join(BASE, 'live-intel.json'),
    state:       path.join(BASE, 'intel-state.json'),
    graph:       path.join(BASE, 'api', 'intel', 'threat-graph.json'),
    campaigns:   path.join(BASE, 'api', 'intel', 'campaigns.json'),
    reportsIndex: path.join(BASE, 'api', 'intel', 'reports-index.json'),
    cveEnrichment: path.join(BASE, 'api', 'intel', 'cve-enrichment-index.json'),
  };
}

let _cache = {};
let _cacheTime = {};
const CACHE_TTL_MS = 60000; // 1-minute in-process cache

function loadJSON(fileOrData) {
  if (typeof fileOrData !== 'string') {
    // Already-parsed data (Workers branch, see PATHS above) — require()
    // memoized it once, nothing left to cache or read.
    return fileOrData;
  }
  const filePath = fileOrData;
  const now = Date.now();
  if (_cache[filePath] && (now - (_cacheTime[filePath] || 0)) < CACHE_TTL_MS) {
    return _cache[filePath];
  }
  try {
    const fs = require('fs');
    const raw = fs.readFileSync(filePath, 'utf8');
    const data = JSON.parse(raw);
    _cache[filePath] = data;
    _cacheTime[filePath] = now;
    return data;
  } catch (e) {
    console.error(`[INTEL] Failed to load ${filePath}: ${e.message}`);
    return null;
  }
}

// Trust & Verification: Ensure every item has required attestation fields
function attestItem(item) {
  return {
    ...item,
    _trust: {
      source_attribution:  item.source || item.sources || 'SENTINEL APEX v4.0',
      confidence_score:    item.sourceCount >= 2 ? 0.95 : item.cisaKev ? 0.98 : 0.82,
      correlation_count:   item.sourceCount || 1,
      verified_at:         new Date().toISOString(),
      methodology:         'Multi-source correlation, CVSS scoring, KEV verification, IOC extraction',
      platform:            'CYBERDUDEBIVASH SENTINEL APEX v4.0',
    },
  };
}

// FREE tier: actor name + data_confidence.tier only. No explanations, no signals.
function filterFree(item) {
  return {
    id:             item.id,
    title:          item.title,
    description:    (item.description || item.desc || '').slice(0, 150) + (item.description && item.description.length > 150 ? '…  [Upgrade to Pro for full details]' : ''),
    cvss:           item.cvss,
    threat_level:   item.threat_level,
    type:           item.type,
    published:      item.published || item.pubDate,
    exploited:      item.exploited,
    cisa_kev:       item.cisa_kev || item.cisaKev,
    vendor:         item.vendor,
    product:        item.product,
    priority_score: item.priority_score,
    sources_confirmed: item.sources_confirmed,
    // Phase 7: Free tier gets actor name + data tier only — no signals, no breakdown
    actor_attribution: {
      primary_actor: item.actor_attribution?.primary_actor || 'Unknown',
      unattributed:  item.actor_attribution?.unattributed ?? true,
    },
    data_confidence: {
      tier: item.data_confidence?.tier || item._trust ? 'MEDIUM' : 'UNKNOWN',
    },
    _upgrade: 'Full IOCs, MITRE mapping, attribution confidence, explainability, and attack chain available on Pro plan — https://blog.cyberdudebivash.in/pricing.html',
    _trust:   (item._trust || attestItem(item)._trust),
  };
}

// PRO tier: full explanation + confidence, actor without raw signals, scoring without breakdown
function filterPro(item) {
  const attr = item.actor_attribution || {};
  return attestItem({
    ...item,
    description: item.description || item.desc,
    iocs:        (item.iocs || []).slice(0, 50),
    refs:        (item.refs || []).slice(0, 10),
    cves:        item.cves || [],
    report_url:  item.report_url || null,
    // Phase 7: Pro gets full explanation + confidence — no raw signals or all_attributions
    actor_attribution: {
      primary_actor:       attr.primary_actor,
      primary_actor_id:    attr.primary_actor_id,
      primary_confidence:  attr.primary_confidence,
      unattributed:        attr.unattributed,
      attribution_quality: attr.attribution_quality,
      evidence_summary:    attr.evidence_summary,
      // signals and all_attributions are Enterprise-only
    },
    data_confidence: item.data_confidence ? {
      score:      item.data_confidence.score,
      tier:       item.data_confidence.tier,
      suppressed: item.data_confidence.suppressed,
    } : undefined,
    scoring: item.scoring ? {
      priority_score:   item.scoring.priority_score,
      normalized_score: item.scoring.normalized_score,
      threat_level:     item.scoring.threat_level,
      confidence_score: item.scoring.confidence_score,
      reasoning:        item.scoring.reasoning,
      // breakdown is Enterprise-only
    } : undefined,
    _explanation: item._explanation, // Full explanation block for Pro
    _intelligence: item._intelligence ? {
      linked_actors:       item._intelligence.linked_actors,
      campaign_id:         item._intelligence.campaign_id,
      campaign_name:       item._intelligence.campaign_name,
      campaign_severity:   item._intelligence.campaign_severity,
      campaign_item_count: item._intelligence.campaign_item_count,
      enriched_at:         item._intelligence.enriched_at,
    } : undefined,
  });
}

// ENTERPRISE tier: everything — raw signals + scoring.breakdown + all_attributions
function filterEnterprise(item) {
  return attestItem(item);
}

function applyTierFilter(items, tier) {
  switch (dataProfile(tier)) {
    case 'enterprise': return items.map(filterEnterprise);
    case 'pro':        return items.map(filterPro);
    default:           return items.map(filterFree);
  }
}

// Parse + validate pagination params
function parsePagination(query) {
  const page  = Math.max(1, parseInt(query.page || '1', 10));
  const limit = Math.min(100, Math.max(1, parseInt(query.limit || '25', 10)));
  return { page, limit, offset: (page - 1) * limit };
}

// Apply filters from query params
function applyFilters(items, query) {
  let out = [...items];

  if (query.severity) {
    const sev = query.severity.toUpperCase();
    out = out.filter(i => (i.threat_level || '').toUpperCase() === sev);
  }
  if (query.type) {
    const t = query.type.toUpperCase();
    out = out.filter(i => (i.type || '').toUpperCase() === t);
  }
  if (query.exploited === 'true' || query.exploited === '1') {
    out = out.filter(i => i.exploited);
  }
  if (query.cisa_kev === 'true' || query.cisa_kev === '1') {
    out = out.filter(i => i.cisa_kev);
  }
  if (query.min_cvss) {
    const min = parseFloat(query.min_cvss);
    out = out.filter(i => (i.cvss || 0) >= min);
  }
  if (query.from_date) {
    const from = new Date(query.from_date);
    out = out.filter(i => new Date(i.published || 0) >= from);
  }
  if (query.vendor) {
    const v = query.vendor.toLowerCase();
    out = out.filter(i => (i.vendor || '').toLowerCase().includes(v));
  }
  return out;
}

// Main intel loader — used by all endpoints
function getIntel(type, tier, query = {}) {
  const file = PATHS[type] || PATHS.live;
  const data = loadJSON(file);
  if (!data) return { items: [], total: 0, cached: false, error: 'Intel source temporarily unavailable' };

  const raw = data.items || [];
  const filtered = applyFilters(raw, query);
  const { page, limit, offset } = parsePagination(query);
  const paged = filtered.slice(offset, offset + limit);
  const tiered = applyTierFilter(paged.map(applyRecordCorrections), tier);

  return {
    items: tiered,
    pagination: {
      page,
      limit,
      total:       filtered.length,
      total_pages: Math.ceil(filtered.length / limit),
      has_next:    offset + limit < filtered.length,
      has_prev:    page > 1,
    },
    intel_meta: {
      generated_at:    data.generated || data.generatedAt || null,
      total_published: data.total_published || data.totalPublished || 0,
      source_platform: data.source || 'CYBERDUDEBIVASH SENTINEL APEX v4.0',
    },
    tier_info: {
      tier,
      full_access:       tierAtLeast(tier, 'pro'),
      ioc_access:        tierAtLeast(tier, 'pro'),
      detection_rules:   tierAtLeast(tier, 'pro'),
      realtime_feed:     tier === 'enterprise',
      upgrade_url:       tier !== 'enterprise' ? 'https://blog.cyberdudebivash.in/pricing.html' : null,
    },
  };
}

// Additive: attaches real graph relationships (related campaigns/actors/
// correlated CVEs) to a CVE detail response. Pro/enterprise only -- the
// free/starter response shape is completely unchanged by this addition.
// Fails soft: a lookup error never breaks the underlying CVE detail that
// was already found.
function attachCveRelated(item, cveId, tier) {
  if (!tierAtLeast(tier, 'pro')) return item;
  try {
    const related = getCveRelated(loadGraph(), cveId);
    return { ...item, related };
  } catch (e) {
    console.error(`[INTEL] CVE related-entity lookup failed for ${cveId}: ${e.message}`);
    return item;
  }
}

// CVE detail lookup across all intel files
function getCVEDetail(cveId, tier) {
  const normalized = cveId.toUpperCase().trim();
  // Try dedicated CVE file first (Node/Vercel only -- `path`/`BASE`/`fs`
  // above are block-scoped to the non-Workers branch, and Workers has no
  // filesystem anyway; PATHS.live's bundled data below covers Workers).
  if (!isCloudflareWorkers()) {
    const path = require('path');
    const fs = require('fs');
    const BASE = path.resolve(__dirname, '../../');
    const cvePath = path.join(BASE, 'api', 'intel', 'cve', `${normalized}.json`);
    if (fs.existsSync(cvePath)) {
      const data = applyRecordCorrections(loadJSON(cvePath));
      if (data) {
        const item = dataProfile(tier) === 'enterprise' ? filterEnterprise(data)
                    : dataProfile(tier) === 'pro'        ? filterPro(data)
                    : filterFree(data);
        return { found: true, item: attachCveRelated(attestItem(item), normalized, tier) };
      }
    }
  }
  // Fall back to scanning live feed
  const live = loadJSON(PATHS.live);
  if (live && live.items) {
    const found = applyRecordCorrections(live.items.find(i => (i.id || '').toUpperCase() === normalized));
    if (found) {
      const item = dataProfile(tier) === 'enterprise' ? filterEnterprise(found)
                  : dataProfile(tier) === 'pro'        ? filterPro(found)
                  : filterFree(found);
      return { found: true, item: attachCveRelated(attestItem(item), normalized, tier) };
    }
  }
  return { found: false, item: null };
}

// Full-text search across live intel
function searchIntel(query, tier, params = {}) {
  const q = String(query || '').toLowerCase().trim();
  if (!q || q.length < 2) return { items: [], total: 0, query };
  const live = loadJSON(PATHS.live);
  if (!live || !live.items) return { items: [], total: 0, query };
  const matches = live.items.filter(item => {
    const text = [item.id, item.title, item.description, item.vendor, item.product, item.type]
      .join(' ').toLowerCase();
    return text.includes(q);
  });
  const { page, limit, offset } = parsePagination(params);
  const paged = matches.slice(offset, offset + limit);
  return {
    items:      applyTierFilter(paged.map(applyRecordCorrections), tier),
    total:      matches.length,
    query,
    pagination: { page, limit, total: matches.length, total_pages: Math.ceil(matches.length / limit) },
  };
}

// Platform stats (public — used by dashboard)
function getPlatformStats() {
  const state = loadJSON(PATHS.state) || {};
  const live  = loadJSON(PATHS.liveWidget) || {};
  const st    = live.stats || {};
  return {
    total_published:  state.totalPublished || 0,
    last_run:         state.lastRun || null,
    version:          state.version || '4.0',
    live_intel_count: (live.items || []).length,
    critical_threats: st.critical || 0,
    cisa_kev_count:   st.cisaKev  || 0,
    exploited_count:  st.exploited || 0,
    ransomware_count: st.ransomware || 0,
  };
}

/* ═══════════════════════════════════════════════════════════════════════
   THREAT GRAPH  — serves pre-built graph.json with tier filtering
═══════════════════════════════════════════════════════════════════════ */
const { getGraphForTier, getTopActors, loadGraph: loadPersistedGraph } = require('./threat-graph');
const { projectGraph } = require('./ioc-engine/feed');

// Every customer-facing graph read (graph, search, IOC/actor detail,
// dossiers) goes through this serving projection: IOC nodes without
// evidence-engine provenance (legacy regex-derived values, ICF-P0-009) are
// removed and evidence-backed feed indicators are added. The persisted
// graph file itself is not modified.
function loadGraph() {
  return projectGraph(loadPersistedGraph());
}

function getGraph(tier) {
  try {
    const graph = loadGraph();
    if (!graph || !graph.nodes) {
      return { nodes: [], edges: [], stats: {}, error: 'Graph not yet built — run fetch-live-intel.js' };
    }
    const result = getGraphForTier(graph, tier);
    if (tier === 'free' || tier === 'starter') {
      result._upgrade = 'Full graph (IOC nodes, malware nodes, all edges) available on Pro/Enterprise — https://blog.cyberdudebivash.in/pricing.html';
    }
    return result;
  } catch (e) {
    console.error(`[INTEL] Graph load error: ${e.message}`);
    return { nodes: [], edges: [], stats: {}, error: 'Graph temporarily unavailable' };
  }
}

/* ═══════════════════════════════════════════════════════════════════════
   CAMPAIGNS  — serves pre-built campaigns.json with tier and pagination
═══════════════════════════════════════════════════════════════════════ */
function getCampaigns(tier, query = {}) {
  const data = loadJSON(PATHS.campaigns);
  if (!data || !data.campaigns) {
    return { campaigns: [], total: 0, error: 'Campaigns not yet built' };
  }

  let campaigns = [...(data.campaigns || [])];

  // Filter
  if (query.severity) {
    const sev = query.severity.toUpperCase();
    campaigns = campaigns.filter(c => c.severity === sev);
  }
  if (query.has_kev === 'true') {
    campaigns = campaigns.filter(c => c.has_kev);
  }
  if (query.has_ransomware === 'true') {
    campaigns = campaigns.filter(c => c.has_ransomware);
  }

  const total  = campaigns.length;
  const { page, limit, offset } = parsePagination(query);
  const paged  = campaigns.slice(offset, offset + limit);

  // Tier gating on shared_iocs, related_intel depth, and reasoning (Phase 7)
  const tierPaged = paged.map(campaign => {
    if (tier === 'free' || tier === 'starter') {
      const { shared_iocs, related_intel, reasoning, clustering_model, ...safe } = campaign;
      return {
        ...safe,
        related_intel: (related_intel || []).slice(0, 3),
        shared_iocs:   [],
        _upgrade: 'Full IOC list, clustering reasoning, and campaign details available on Pro plan',
      };
    }
    if (tier === 'pro') {
      return { ...campaign, shared_iocs: (campaign.shared_iocs || []).slice(0, 20) };
    }
    return campaign; // enterprise: everything including reasoning[] and clustering_model
  });

  return {
    campaigns: tierPaged,
    total,
    pagination: { page, limit, total, total_pages: Math.ceil(total / limit), has_next: offset + limit < total },
    generated: data.generated,
    tier_info: { tier, full_ioc_access: tierAtLeast(tier, 'pro') },
  };
}

function getCampaignDetail(campaignId, tier) {
  const data = loadJSON(PATHS.campaigns);
  if (!data || !data.campaigns) return { found: false, campaign: null };

  const normalizedId = String(campaignId || '').toLowerCase();
  const campaign = data.campaigns.find(c =>
    c.campaign_id === normalizedId ||
    c.campaign_id === `campaign:${normalizedId}` ||
    c.campaign_id.includes(normalizedId)
  );

  if (!campaign) return { found: false, campaign: null };

  if (tier === 'free' || tier === 'starter') {
    const { shared_iocs, ...safe } = campaign;
    return { found: true, campaign: { ...safe, shared_iocs: [], _upgrade: 'IOC list requires Pro plan' } };
  }
  return { found: true, campaign };
}

function getTopActorsAPI(tier, limit = 10) {
  try {
    const graph = loadGraph();
    if (!graph || !graph.nodes) return { actors: [], error: 'Graph not yet built' };
    const actors = getTopActors(graph, Math.min(20, parseInt(limit, 10)));

    // Tier gating on actor detail
    const tiered = actors.map(actor => {
      if (tier === 'free' || tier === 'starter') {
        return {
          id:               actor.id,
          name:             actor.name,
          category:         actor.attributes?.category,
          motivation:       actor.attributes?.motivation,
          activity_score:   actor.activity_score,
          cve_count:        actor.cve_count,
          active:           actor.attributes?.active,
          _upgrade:         'Full TTP mapping, target sectors, and IOC relationships on Pro plan',
        };
      }
      return actor; // pro + enterprise: full detail
    });

    return {
      actors: tiered,
      total:  actors.length,
      generated: graph.generated,
    };
  } catch (e) {
    return { actors: [], error: 'Actor data temporarily unavailable' };
  }
}

/* ═══════════════════════════════════════════════════════════════════════
   UNIFIED INTELLIGENCE SEARCH  — derived, in-memory, cached projection
   over the graph/campaigns/reports already loaded above. No second
   persisted store: see api/_lib/search-index.js's own header for why.
═══════════════════════════════════════════════════════════════════════ */
const {
  buildSearchIndex, validateSearchIndex, searchDocuments,
  getActorDetail, getIocDetail, getReportDetail, getCveRelated,
} = require('./search-index');

let _searchIndexCache = null;
let _searchIndexCacheTime = 0;
const SEARCH_INDEX_CACHE_TTL_MS = 60000; // matches CACHE_TTL_MS above

function getSearchIndex() {
  const now = Date.now();
  if (_searchIndexCache && (now - _searchIndexCacheTime) < SEARCH_INDEX_CACHE_TTL_MS) {
    return _searchIndexCache;
  }
  const graph          = loadGraph();
  const campaignsData  = loadJSON(PATHS.campaigns);
  const reportsIndexData = loadJSON(PATHS.reportsIndex);
  const index = buildSearchIndex({ graph, campaignsData, reportsIndexData });

  const check = validateSearchIndex(index, { graph, campaignsData, reportsIndexData });
  if (!check.valid) {
    // Fail safe, not fail closed: an anomaly here means the computed
    // index disagrees with its own canonical inputs (the exact failure
    // class the campaign-delivery-integrity-v1 fix exists to catch) —
    // log loudly and keep serving the previous good cache rather than a
    // suspect one, matching this file's own PATHS.campaigns caution.
    console.error(`[SEARCH-INDEX] Validation failed: ${check.problems.join('; ')}`);
    if (_searchIndexCache) return _searchIndexCache;
  }

  _searchIndexCache = index;
  _searchIndexCacheTime = now;
  return index;
}

function unifiedSearch(query, tier, options = {}) {
  const index = getSearchIndex();
  return searchDocuments(index, query, { ...options, tier });
}

function getActorDetailAPI(actorId) {
  return getActorDetail(loadGraph(), actorId);
}

function getIocDetailAPI(iocId) {
  return getIocDetail(loadGraph(), iocId);
}

function getReportDetailAPI(reportId) {
  return getReportDetail(loadJSON(PATHS.reportsIndex), reportId);
}

/* ═══════════════════════════════════════════════════════════════════════
   INTELLIGENCE DOSSIER  — evidence-backed, decision-oriented projection
   over the same canonical CVE/Campaign data above. Not a new store: see
   api/_lib/intelligence-dossier.js's own header for the full contract.
═══════════════════════════════════════════════════════════════════════ */
const { buildCveDossier, buildCampaignDossier } = require('./intelligence-dossier');

const DOSSIER_SUPPORTED_TYPES = new Set(['cve', 'campaign']);

function getDossierAPI(type, id, tier) {
  const normalizedType = String(type || '').toLowerCase().trim();
  if (!DOSSIER_SUPPORTED_TYPES.has(normalizedType)) {
    return { found: false, dossier: null, unsupported: true };
  }

  const graph = loadGraph();
  const reportsIndexData = loadJSON(PATHS.reportsIndex);

  if (normalizedType === 'cve') {
    const cveId = String(id || '').toUpperCase().trim();
    const { found, item } = getCVEDetail(cveId, tier);
    if (!found) return { found: false, dossier: null, unsupported: false };
    const enrichmentData = loadJSON(PATHS.cveEnrichment);
    const enrichment = (enrichmentData && enrichmentData.entries) ? (enrichmentData.entries[cveId] || null) : null;
    const dossier = buildCveDossier({ graph, cveId, cveItem: item, enrichment, reportsIndexData, tier });
    return { found: true, dossier, unsupported: false };
  }

  // normalizedType === 'campaign'
  const { found, campaign } = getCampaignDetail(id, tier);
  if (!found) return { found: false, dossier: null, unsupported: false };
  const dossier = buildCampaignDossier({ graph, campaign, reportsIndexData, tier });
  return { found: true, dossier, unsupported: false };
}

module.exports = {
  getIntel, getCVEDetail, searchIntel, getPlatformStats, applyTierFilter,
  getGraph, getCampaigns, getCampaignDetail, getTopActorsAPI,
  loadJSON, loadGraph, PATHS, parsePagination, attestItem,
  getSearchIndex, unifiedSearch, getActorDetailAPI, getIocDetailAPI, getReportDetailAPI,
  getDossierAPI,
};
